const int MPI_TAG_GRAPH_PROCESSING_DONE				= 10;
const int MPI_TAG_GRAPH_REQUEST_HELP				= 11;
const int MPI_TAG_GRAPH_REQUEST_HELP_RESPONSE		= 12;
const int MPI_TAG_GRAPH_HELP_DATA_DEPTH				= 13;
const int MPI_TAG_GRAPH_HELP_DATA_BASE_NODES		= 14;
const int MPI_TAG_GRAPH_HELP_DATA_POTENTIAL_NODES	= 15;
const int MPI_TAG_GRAPH_HELP_DATA_START				= 16;
const int MPI_TAG_GRAPH_HELP_DATA_END				= 17;
const int MPI_TAG_ALL_PROCESSING_COMPLETED			= 18;
const int MPI_TAG_CLIQUE_COUNTS						= 19;
const int MPI_TAG_HELP_REQUESTS_SENT				= 20;
const int MPI_TAG_HELP_REQUESTS_SENT_ACCEPTED		= 21;
const int MPI_TAG_HELP_REQUESTS_SENT_REJECTED		= 22;

const int PROCESS_IDLE = 0;
const int PROCESS_RUNNING = 1;
const int PROCESS_HELPING = 2;